services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hutang_db
      MYSQL_USER: hutang_user
      MYSQL_PASSWORD: hutang_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./hutang_db.sql:/docker-entrypoint-initdb.d/hutang_db.sql:ro

volumes:
  db_data:
